name: main
on: push


jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64' 
      - name: test get-function
        run: cd get-function && python test.py -v ./ && cd ../../
      - name: test put-function
        run: cd put-function && python test.py -v ./ && cd ../../

      